[package]
name = "steaks"
version = "0.1.0"
authors = ["Tibor Nagy <xnagytibor@gmail.com>"]

[dependencies]
byteorder = "1.0.0"
clap = "2.24.2"
gba-rs = { git = "https://github.com/xtibor/gba-rs" }
serde = "1.0.7"
serde_derive = "1.0.7"
serde_json = "1.0"

